# Generated by Django 3.1.5 on 2021-02-19 01:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=8, unique=True, verbose_name='Slug')),
                ('air_date', models.DateField(verbose_name='Air Date')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('location', models.CharField(max_length=255)),
                ('banner_url', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Banner URL')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-air_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('Μέγας', 'Μέγας'), ('Xρυσός', 'Xρυσός'), ('Αργυρός', 'Αργυρός'), ('Χάλκινος', 'Χάλκινος')], max_length=8, null=True, verbose_name='Type')),
                ('logo_url', models.ImageField(upload_to='', verbose_name='Logo URL')),
                ('brand_url', models.URLField(verbose_name='Brand URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(verbose_name='url')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
                'db_table': 'socials',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='main_site.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('photo_url', models.ImageField(upload_to='', verbose_name='Photo URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_site.role', verbose_name='Role')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_site.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='EventWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('air_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Air Date & Time')),
                ('banner_url', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='Banner URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='main_site.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'db_table': 'event_workshops',
                'ordering': ['-air_date_time'],
            },
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main_site.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'event_videos',
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=255, upload_to='', verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_site.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'event_photos',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('air_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Air Date & Time')),
                ('occupation', models.CharField(max_length=255, verbose_name='Occupation')),
                ('type', models.CharField(choices=[('Speaker', 'Speaker'), ('Host', 'Host'), ('Performance', 'Performance')], default='Speaker', max_length=20, verbose_name='Type')),
                ('category', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Design', 'Design'), ('Business', 'Business')], default='Technology', max_length=20, null=True, verbose_name='Category')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main_site.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'event_participants',
                'ordering': ['-air_date_time'],
            },
        ),
    ]
