# Generated by Django 3.1.5 on 2021-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
        migrations.AddField(
            model_name='eventworkshop',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='2020-2021', max_length=9, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('platinum', 'Platinum Partner'), ('gold', 'Gold Partner'), ('silver', 'Silver Partner'), ('bronze', 'Bronze Partner'), ('in_kind', 'In Kind'), ('media', 'Media Partner'), ('friend', 'Friend')], max_length=8, null=True, verbose_name='Type'),
        ),
    ]
