# Generated by Django 3.2.8 on 2021-11-27 18:50

from django.db import migrations, models
import django.utils.timezone
import main_site.models_extras
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20210427_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('banner', models.URLField(max_length=255, null=True, verbose_name='Banner')),
                ('article', tinymce.models.HTMLField(verbose_name='Article')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Design', 'Design'), ('Business', 'Business')], default='Technology', max_length=13, verbose_name='Category')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='2021-2022', max_length=9, validators=[main_site.models_extras.member_slug], verbose_name='Slug'),
        ),
    ]
