# Generated by Django 3.2.8 on 2022-01-10 21:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20211127_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=ckeditor.fields.RichTextField(verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
